### ISSUE TITLE
Example error: unable to resolve interopRequireDefault

### ISSUE THREAD

**Issue by dancesWithCycles** [YsnKsy/react-native-location-enabler#33]
Hi folks,
thank you so much for maintaining this repository. The documentation sounds promising. That is why I wanted to see it with my own eyes and tried it straight by myself. However, I could not run the example without errors. I ran these instructions.
```
yarn example
yarn example start
yarn example android
```
The result is the following error message from metro bundler:
```
[Fri Mar 26 2021 08:56:54.963]  BUNDLE  ./index.tsx 

error: Error: Unable to resolve module `@babel/runtime/helpers/interopRequireDefault` from `../src/index.ts`: @babel/runtime/helpers/interopRequireDefault could not be found within the project.

If you are sure the module exists, try these steps:
 1. Clear watchman watches: watchman watch-del-all
 2. Delete node_modules: rm -rf node_modules and run yarn install
 3. Reset Metro's cache: yarn start --reset-cache
 4. Remove the cache: rm -rf /tmp/metro-*
    at ModuleResolver.resolveDependency (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:186:15)
    at ResolutionRequest.resolveDependency (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:52:18)
    at DependencyGraph.resolveDependency (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/node-haste/DependencyGraph.js:287:16)
    at Object.resolve (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/lib/transformHelpers.js:267:42)
    at /home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:434:31
    at Array.map (<anonymous>)
    at resolveDependencies (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:431:18)
    at /home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:275:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/home/stefan/git/react-native-location-enabler/example/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
```
I also ran the four recommended steps from the error message without any change. First I thought this error might be due to metro bundler is not reading TypeScript. That is why I added this snippet to the metro configuration.
```
/*by default metro bundler does not compile files with extension .ts or .tsx*/
sourceExts:['jsx','js','ts','tsx'],
```
This configuration change also did not yield the desired effect. I am working with an Ubuntu 18.04 operating system with the following dev tool versions.
```
yarn --version 1.22.5
node --version v14.16.0
```
I checked out this repository as it is now at the time I am writing this issue. Does anyone can point me in the right direction? Cheers!

**Comment by YsnKsy** [comment]
Hi @dancesWithCycles 

Please run `react-native info` in your terminal and copy the results here.

Thank you ;)

**Comment by dancesWithCycles** [comment]
Here you are:
```
cd example/
/git/react-native-location-enabler/example$ react-native info
info Fetching system and libraries information...
(node:9506) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
System:
    OS: Linux 4.15 Trisquel GNU/Linux 9.0, Etiona
    CPU: (4) x64 Intel(R) Core(TM) i3 CPU       M 330  @ 2.13GHz
    Memory: 785.93 MB / 7.47 GB
    Shell: 4.4.20 - /bin/bash
  Binaries:
    Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
    Yarn: 1.22.5 - /usr/bin/yarn
    npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 28, 29
      Build Tools: 28.0.3, 29.0.2, 29.0.3
      Android NDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_282 - /home/stefan/devTools/jdk/jdk8u282-b08/bin/javac
    Python: 2.7.17 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.11.0 => 16.11.0 
    react-native: 0.62.2 => 0.62.2 
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by YsnKsy** [comment]
Hi @dancesWithCycles

Please run these instructions it should work ;)

```
yarn 
yarn example start
yarn example android
```

Thank you :)
